// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
#import "template.typ": *

#show: resume.with(
  name: "Murtaza S. Ahmed",
  title: "Embedded & Distributed Systems Engineer (Infrastructure focus)",
  email: "murtazaofficial@proton.me",
  phone: "+91 9390341984",
  website: "https://onerealti.github.io/portfolio",
  github: "https://github.com/onerealti",
  linkedin: "https://linkedin.com/in/onerealti",
  summary: "Computer Engineering student specializing in embedded edge AI systems, distributed systems development, and backend infrastructure. Experienced in TensorRT-accelerated inference pipelines on NVIDIA Jetson Nano, decentralized media provenance protocols using IPFS/Arweave, and deterministic Linux system provisioning.",
)

= Professional Experience
#exp-item(
  company: "Department of Mechanical Engineering (MJCET)",
  role: "Undergraduate Research Assistant (Edge AI Systems)",
  location: "Hyderabad, TG",
  date: "Dec 2025 -- Present",
  bullets: ("Developed an embedded edge AI platform using an NVIDIA Jetson Nano, IMX719 camera module, and telemetry sensors.", "Optimized computer vision inference pipelines using TensorRT FP16 acceleration, achieving 40-70 ms latency (14-20 FPS) under constrained compute environments.", "Implemented deterministic execution and monitoring systems for stable long-duration deployment.", "Researched adaptive workload scheduling and hardware-aware resource allocation strategies for heterogeneous LLM inference systems in interdepartmental R&D program.", "Exploring fault-tolerant orchestration approaches for distributed AI workloads across mixed compute environments."),
)

#exp-item(
  company: "Verity (Decentralized Verification Platform)",
  role: "Builder & Systems Architect",
  location: "Hyderabad, TG",
  date: "July 2025 -- Present",
  bullets: ("Designing and implementing system to verify digital media provenance using blockchain and decentralized storage.", "Integrating AI modules for manipulation detection and automated claim extraction.", "Developing media provenance infrastructure using distributed storage systems including IPFS and Arweave.", "Building concurrent ingestion pipelines and immutable audit logging mechanisms for ML-based verification workflows."),
)

#exp-item(
  company: "Freelance Consulting",
  role: "Backend Infrastructure Engineer",
  location: "Hyderabad, TG",
  date: "Sept 2024 -- Present",
  bullets: ("Migrated client applications to containerized Linux deployment environments with automated CI/CD workflows.", "Designed backend APIs and optimized PostgreSQL schemas for improved concurrency and deployment reliability."),
)

= Projects
#proj-item(
  title: "Smart Agri Four-Legged Bot (SAFL-B)",
  skills: ("C", "Python", "UART/Serial", "I2C", "GPIO", "Hardware Control"),
  date: "Dec 2025",
  bullets: ("Awarded 1st Place at the MAKEFORHYDERABAD 2-Day Makeathon for autonomous robotics systems integration.", "Implemented deterministic UART/Serial communication protocols for multi-joint motor control.", "Developed telemetry stabilization routines to reduce terrain-induced sensor and image noise."),
)

#proj-item(
  title: "Deterministic Workspace Provisioning",
  skills: ("Bash", "Linux", "Arch Linux", "Podman", "Git"),
  date: "June 2025",
  bullets: ("Built automated provisioning pipelines for lightweight Linux workstation deployment using Arch Linux and shell automation.", "Configured container runtimes (Docker/Podman) and developer tools to deploy reproducible workspace layers."),
)

= Technical Skills
#skill-category(
  category: "Languages",
  items: ("C", "Python", "Bash", "PostgreSQL", "Git"),
)
#skill-category(
  category: "Systems",
  items: ("Linux", "Arch Linux", "Docker", "Kubernetes", "Podman"),
)

= Education
#edu-item(
  institution: "Muffakham Jah College of Engineering & Technology (Osmania University)",
  degree: "Bachelor of Engineering",
  location: "Hyderabad, TG",
  date: "Sept 2024 -- May 2028",
  gpa: "8.9/10.0",
  details: ("Relevant Coursework: Scientific Computing, Embedded Systems Programming, System Modeling & Simulation", "Exploring adaptive resource scheduling and heterogeneous LLM inference orchestrators"),
)

