// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
#import "template.typ": *

#show: resume.with(
  name: "Murtaza Ahmed",
  title: "Undergrad Engineer | Distributed Systems, ML Systems & Infra (Distributed focus)",
  email: "murtazaofficial@protonmail.com",
  phone: "+91 9390341984",
  website: "https://onerealti.github.io/portfolio",
  github: "https://github.com/onerealti",
  linkedin: "https://www.linkedin.com/in/murahmed",
  summary: "I'm a systems engineer and undergraduate researcher focused on building the future of AI infrastructure. I design resilient cluster orchestration policy engines, optimize edge computer vision pipelines, and build custom hardware platforms. Welcome to my digital workspace—feel free to check out my latest research, open-source projects, or download my typeset resumes!",
)

= EDUCATION
#edu-item(
  institution: "Muffakham Jah College of Engineering & Technology (Osmania University)",
  degree: "Bachelor of Engineering in Mechanical Engineering",
  location: "Hyderabad, TG",
  date: "May 2028",
  gpa: "",
  details: ("Relevant Coursework: Scientific Computing, Embedded Systems Programming, System Modeling & Simulation",),
)

= EXPERIENCE
#exp-item(
  company: "Department of Mechanical Engineering (MJCET)",
  role: "Undergraduate Research Assistant (Edge AI Systems)",
  location: "Hyderabad, TG",
  date: "Dec 2025 -- Present",
  bullets: ("Selected for an institution-funded R&D program under faculty supervision.", "Built a complete edge AI system on NVIDIA Jetson Nano 4GB Developer Kit, integrating an IMX719 camera and soil sensors for real-time field operation.", "Developed the on-device inference pipeline and executed real-time inference under compute and memory constraints.", "Achieved 40–70 ms latency (14–20 FPS) using TensorRT (FP16) optimization.", "Processed camera and sensor data continuously at 5–10 Hz with low-latency performance.", "Designed a stable execution loop enabling reliable operation over 4–6 hour field deployments."),
)

#exp-item(
  company: "Department of Mechanical Engineering (MJCET)",
  role: "Undergraduate Researcher (R&D Program)",
  location: "Hyderabad, TG",
  date: "March 2026 -- Present",
  bullets: ("Design and implementation of an Adaptive Multi-Objective Policy Engine for Resilient Orchestration in Heterogeneous LLM Clusters.", "Researching adaptive workload scheduling and hardware-aware resource allocation strategies for heterogeneous LLM inference systems.", "Exploring fault-tolerant orchestration approaches for distributed AI workloads across mixed compute environments."),
)

#exp-item(
  company: "Verity (Decentralized Verification Platform)",
  role: "Builder & Systems Architect",
  location: "Hyderabad, TG",
  date: "July 2025 -- Present",
  bullets: ("Designing and implementing a system to verify digital media provenance using blockchain and decentralized storage.", "Integrating AI modules for manipulation detection and automated claim extraction.", "Developing media provenance infrastructure using distributed storage systems including IPFS and Arweave.", "Building concurrent ingestion pipelines and immutable audit logging mechanisms for ML-based verification workflows."),
)

= PROJECTS
#proj-item(
  title: "Smart Agri Four-Legged Bot (SAFL-B)",
  skills: ("C", "Python", "TensorRT", "NVIDIA Jetson Nano", "Arduino Due", "SolidWorks", "FEA", "UART/Serial"),
  date: "May 2026",
  bullets: ("Awarded 1st Place at the city-wide MAKEFORHYDERABAD Makeathon (organized by Titan & SIT Hyderabad) for autonomous robotics integration.", "Designed a hybrid 3mm steel chassis and custom 3D-printed modular articulated planar legs featuring passive compliance and internal wire routing channels.", "Validated structural load paths using Finite Element Analysis (FEA) under static vertical loads, bumps, and probe insertions with a minimum safety factor of 2.04.", "Integrated a local CNN weed classification model on NVIDIA Jetson Nano, achieving real-time inference (9.2 FPS) using TensorRT FP16 acceleration.", "Designed low-level kinematic control systems using an Arduino Due to orchestrate H-Bridge DC motor actuators and high-current ESCs."),
)

= TOOLS & METHODS
#skill-category(
  category: "Languages",
  items: ("C", "Python", "Bash", "PostgreSQL", "Git"),
)
#skill-category(
  category: "Systems",
  items: ("Linux", "Docker", "Kubernetes"),
)
#skill-category(
  category: "ML/Edge Computing",
  items: ("TensorRT", "NVIDIA Jetson Nano"),
)
#skill-category(
  category: "Hardware & Interfaces",
  items: ("UART/Serial", "I2C", "GPIO"),
)

