// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
#import "template.typ": *

#show: resume.with(
  name: "Alex Rivers",
  title: "Systems & Infrastructure Engineer (Infrastructure focus)",
  email: "alex.rivers@example.com",
  phone: "+1 (555) 019-2834",
  website: "https://alexrivers.dev",
  github: "https://github.com/alexrivers",
  linkedin: "https://linkedin.com/in/alex-rivers",
  summary: "Computer Science student specializing in distributed systems, storage engines, and ML training infrastructure. Experienced in building transactional key-value databases, implementing consensus algorithms, and optimizing high-throughput data processing pipelines. Passionate about kernel development, low-latency network programming, and platform automation.",
)

= Professional Experience
#exp-item(
  company: "KernelCorp Technologies",
  role: "Systems & Linux Kernel Intern",
  location: "San Jose, CA (Remote)",
  date: "May 2025 -- Aug 2025",
  bullets: ("Designed and implemented an eBPF/XDP-based load-balancer that reduced packet processing latency by 35% compared to IPVS-based routing.", "Patched network driver queues to optimize cache-line utilization, resulting in a 12% increase in packet throughput for 100GbE interfaces.", "Developed a Linux Kernel Module (LKM) for virtual device drivers to mock high-frequency sensors for CI/CD test automation.", "Collaborated with upstream developers to patch a race condition in kernel slab memory allocation under heavy network load."),
)

#exp-item(
  company: "StoreScale Systems",
  role: "Distributed Storage Intern",
  location: "Seattle, WA",
  date: "May 2024 -- Aug 2024",
  bullets: ("Integrated RocksDB as a pluggable storage engine for a custom Raft-based transactional database, improving write throughput by 40%.", "Engineered an asynchronous log-compaction pipeline in Go to reduce tail latency of client writes under disk I/O bottlenecks.", "Built a cluster simulation framework to perform partition testing (Jepsen-style) and validated correctness of linearizable reads.", "Optimized gRPC request-serialization paths using Protobuf custom-marshaling, achieving an 18% reduction in CPU utilization."),
)

= Projects
#proj-item(
  title: "TensorFlow & PyTorch ML Training Orchestrator",
  skills: ("Python", "PyTorch", "Kubernetes", "CUDA", "gRPC", "Docker"),
  date: "Mar 2025",
  bullets: ("Developed a custom Kubernetes controller in Go that schedules distributed PyTorch training jobs across multiple GPU-enabled nodes.", "Configured torch.distributed tensor-parallel setups with custom communication primitives, optimizing NCCL ring-allreduce performance.", "Implemented a dynamic fault-recovery agent that restarts failed worker pods, restoring from latest weights checkpoints in under 30 seconds.", "Designed an active GPU allocation scheduler that schedules training jobs to maximize NVLink interconnect bandwidth between GPUs."),
)

#proj-item(
  title: "Distributed Raft Consensus Engine",
  skills: ("Go", "Raft", "gRPC", "Protobuf", "Linearizability", "Jepsen"),
  date: "Dec 2024",
  bullets: ("Built a complete Raft consensus module in Go supporting leader election, log replication, and safe cluster state transitions.", "Implemented a lease-based read optimization and read-index queries to support linearizable reads without full roundtrip consensus.", "Designed a custom snapshotting mechanism and log compaction process to reclaim disk space, preventing memory bloat on large clusters.", "Passed Jepsen partition tests, simulating network split-brain scenarios and validating that data remains consistent and serializable."),
)

#proj-item(
  title: "AetherDB: MVCC Key-Value Engine",
  skills: ("C++", "LSM-Tree", "MVCC", "POSIX", "WAL", "Transactions"),
  date: "May 2024",
  bullets: ("Designed an LSM-Tree storage layout in C++ with MemTable, Write-Ahead Log (WAL), and multi-tiered SSTables for fast writes.", "Implemented a lock-free Multi-Version Concurrency Control (MVCC) system using atomic hardware pointers, ensuring snapshot isolation.", "Programmed custom merge-compaction threads using POSIX APIs, reducing storage footprint by 45% and eliminating compaction spikes.", "Engineered an instant recovery algorithm scanning WAL files, restoring database state in under 150ms after abrupt shutdowns."),
)

= Technical Skills
#skill-category(
  category: "Tools",
  items: ("Git & GitHub Actions", "Prometheus & Grafana"),
)
#skill-category(
  category: "Systems & Infrastructure",
  items: ("Linux Kernel", "Kubernetes", "gRPC & Protobuf", "eBPF / XDP", "PostgreSQL & Redis", "Docker"),
)
#skill-category(
  category: "Languages",
  items: ("Rust", "C++", "Go", "Python", "C"),
)

= Education
#edu-item(
  institution: "Tech Institute of Technology",
  degree: "Bachelor of Science",
  location: "Boston, MA",
  date: "Sept 2023 -- May 2027",
  gpa: "3.95/4.00",
  details: ("Teaching Assistant: Distributed Systems (CS 452), Operating Systems (CS 321)", "Coursework: Distributed Systems, Database Internals, Compiler Construction, Computer Architecture, Advanced Networks"),
)

