import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import * as yaml from "js-yaml";
import { z } from "zod";
import {
  ProfileSchema,
  ExperienceSchema,
  EducationSchema,
  ProjectSchema,
  SkillSchema,
} from "../src/lib/schemas";
import type {
  Profile,
  Experience,
  Education,
  Project,
  Skill,
} from "../src/lib/schemas";

const CONTENT_DIR = path.join(process.cwd(), "src/content");
const RESUME_DIR = path.join(process.cwd(), "resume");
const PUBLIC_DIR = path.join(process.cwd(), "public");

// Ensure directories exist
if (!fs.existsSync(RESUME_DIR)) fs.mkdirSync(RESUME_DIR);
if (!fs.existsSync(PUBLIC_DIR)) fs.mkdirSync(PUBLIC_DIR);

function parseMarkdownFrontmatter<T>(filePath: string, schema: z.ZodTypeAny): T {
  const content = fs.readFileSync(filePath, "utf-8");
  const parts = content.split(/^---$/m);
  if (parts.length < 3) {
    throw new Error(`Invalid markdown frontmatter in: ${filePath}`);
  }
  const rawYaml = parts[1];
  const parsed = yaml.load(rawYaml);
  return schema.parse(parsed) as T;
}

function loadJSON<T>(filePath: string, schema: z.ZodTypeAny): T {
  const raw = fs.readFileSync(filePath, "utf-8");
  const parsed = JSON.parse(raw);
  return schema.parse(parsed) as T;
}

// Load profile
const profileFile = path.join(CONTENT_DIR, "profile/me.json");
const profile = loadJSON<Profile>(profileFile, ProfileSchema);

// Load experience
const expDir = path.join(CONTENT_DIR, "experience");
const experienceList = fs.readdirSync(expDir)
  .filter(f => f.endsWith(".md") || f.endsWith(".mdx"))
  .map(f => parseMarkdownFrontmatter<Experience>(path.join(expDir, f), ExperienceSchema));

// Load education
const eduDir = path.join(CONTENT_DIR, "education");
const educationList = fs.readdirSync(eduDir)
  .filter(f => f.endsWith(".md") || f.endsWith(".mdx"))
  .map(f => parseMarkdownFrontmatter<Education>(path.join(eduDir, f), EducationSchema));

// Load projects
const projDir = path.join(CONTENT_DIR, "projects");
const projectsList = fs.readdirSync(projDir)
  .filter(f => f.endsWith(".md") || f.endsWith(".mdx"))
  .map(f => parseMarkdownFrontmatter<Project>(path.join(projDir, f), ProjectSchema))
  .filter(p => !p.draft);

// Load skills
const skillsDir = path.join(CONTENT_DIR, "skills");
const skillsList = fs.readdirSync(skillsDir)
  .filter(f => f.endsWith(".json"))
  .map(f => loadJSON<Skill>(path.join(skillsDir, f), SkillSchema));

// Generate Typst code for a given profile variant
function generateTypstMarkup(variant: string): string {
  // 1. Filter and sort experience
  const filteredExperience = experienceList
    .filter(e => e.profiles.includes(variant))
    .sort((a, b) => (a.importance ?? 10) - (b.importance ?? 10));

  // 2. Filter and sort education (all are global, sort by importance)
  const sortedEducation = educationList
    .sort((a, b) => (a.importance ?? 10) - (b.importance ?? 10));

  // 3. Filter and sort projects
  const filteredProjects = projectsList
    .filter(p => p.profiles.includes(variant))
    .sort((a, b) => (a.importance ?? 10) - (b.importance ?? 10));

  // 4. Filter and sort skills, grouped by category
  const filteredSkills = skillsList
    .filter(s => s.profiles.includes(variant))
    .sort((a, b) => (a.importance ?? 10) - (b.importance ?? 10));

  // Group skills by category
  const skillsByCategory: Record<string, string[]> = {};
  filteredSkills.forEach(s => {
    if (!skillsByCategory[s.category]) {
      skillsByCategory[s.category] = [];
    }
    skillsByCategory[s.category].push(s.name);
  });

  // Construct markup
  let markup = `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
#import "template.typ": *

#show: resume.with(
  name: "${profile.name}",
  title: "${profile.title} (${variant.charAt(0).toUpperCase() + variant.slice(1)} focus)",
  email: "${profile.email}",
  phone: "${profile.phone}",
  website: "${profile.website}",
  github: "${profile.github}",
  linkedin: "${profile.linkedin}",
  summary: "${profile.summary}",
)

= EDUCATION
`;

  sortedEducation.forEach(edu => {
    const detailsStr = edu.details ? edu.details.map(d => `"${d.replace(/"/g, "\\\"")}"`).join(", ") : "";
    markup += `#edu-item(
  institution: "${edu.institution}",
  degree: "${edu.degree}${edu.fieldOfStudy ? ` in ${edu.fieldOfStudy}` : ""}",
  location: "${edu.location}",
  date: "${edu.dateStart ? `${edu.dateStart} -- ` : ""}${edu.dateEnd}",
  gpa: "${edu.gpa ?? ""}",
  details: (${detailsStr}${edu.details && edu.details.length === 1 ? "," : ""}),
)
\n`;
  });

  markup += `= EXPERIENCE\n`;
  filteredExperience.forEach(exp => {
    const bulletsStr = exp.bullets.map(b => `"${b.replace(/"/g, "\\\"")}"`).join(", ");
    markup += `#exp-item(
  company: "${exp.company}",
  role: "${exp.role}",
  location: "${exp.location}",
  date: "${exp.dateStart} -- ${exp.dateEnd}",
  bullets: (${bulletsStr}${exp.bullets.length === 1 ? "," : ""}),
)
\n`;
  });

  markup += `= PROJECTS\n`;
  filteredProjects.forEach(proj => {
    const bulletsStr = proj.bullets.map(b => `"${b.replace(/"/g, "\\\"")}"`).join(", ");
    const skillsStr = proj.skills.map(s => `"${s}"`).join(", ");
    markup += `#proj-item(
  title: "${proj.title}",
  skills: (${skillsStr}${proj.skills.length === 1 ? "," : ""}),
  date: "${proj.date}",
  bullets: (${bulletsStr}${proj.bullets.length === 1 ? "," : ""}),
)
\n`;
  });

  markup += `= TOOLS & METHODS\n`;
  const categoryOrder = ["Languages", "Systems", "ML/Edge Computing", "Hardware & Interfaces"];
  const sortedCategories = Object.keys(skillsByCategory).sort((a, b) => {
    return categoryOrder.indexOf(a) - categoryOrder.indexOf(b);
  });

  for (const category of sortedCategories) {
    const items = skillsByCategory[category];
    if (!items) continue;
    const itemsStr = items.map(i => `"${i}"`).join(", ");
    markup += `#skill-category(
  category: "${category}",
  items: (${itemsStr}${items.length === 1 ? "," : ""}),
)
`;
  }
  markup += `\n`;

  return markup;
}

// Build all variants
const variants = ["backend", "distributed", "ml", "infrastructure"];
const defaultVariant = "distributed"; // The default resume is the distributed systems one

console.log("🛠️  Generating Typst markup and compiling PDF resumes...");

variants.forEach(variant => {
  try {
    const markup = generateTypstMarkup(variant);
    const typstPath = path.join(RESUME_DIR, `generated-${variant}.typ`);
    
    // Write Typst markup
    fs.writeFileSync(typstPath, markup, "utf-8");
    console.log(`  ✅ Generated Typst file for: ${variant}`);

    // Compile Typst to PDF using local typst binary
    const pdfPath = path.join(PUBLIC_DIR, `resume-${variant}.pdf`);
    const typstCmd = `./bin/typst compile --font-path ./AGPro ${typstPath} ${pdfPath}`;
    execSync(typstCmd, { stdio: "inherit" });
    console.log(`  📄 Compiled PDF for: ${variant} -> public/resume-${variant}.pdf`);

    // If this is the default variant, copy it to resume.typ and resume.pdf
    if (variant === defaultVariant) {
      fs.writeFileSync(path.join(RESUME_DIR, "generated.typ"), markup, "utf-8");
      fs.copyFileSync(pdfPath, path.join(PUBLIC_DIR, "resume.pdf"));
      console.log(`  🌟 Set as default: public/resume.pdf`);
    }
  } catch (err: unknown) {
    console.error(`❌ Failed to compile resume for variant: ${variant}`);
    console.error(err instanceof Error ? err.message : String(err));
  }
});

console.log("\n✨ Resume compilation complete!");
